"""Tests for the rules engine — reading and marker injection logic."""

import json
from pathlib import Path

from runpod_flash.rules.engine import (
    AGENT_FILE_TARGETS,
    generate_agent_files,
    inject_rules_section,
    read_static_rules,
    update_dynamic_context,
)


class TestReadStaticRules:
    def test_returns_string(self):
        content = read_static_rules()
        assert isinstance(content, str)

    def test_contains_version_comment(self):
        content = read_static_rules()
        assert "flash-rules-version" in content

    def test_contains_endpoint_decorator(self):
        content = read_static_rules()
        assert "@Endpoint" in content


class TestInjectRulesSection:
    def test_new_file_creates_full_content(self):
        result = inject_rules_section("", "rules content", "1.9.1")
        assert "FLASH:START" in result
        assert "FLASH:END" in result
        assert "rules content" in result

    def test_existing_file_appends_section(self):
        existing = "# My Project\nCustom instructions here.\n"
        result = inject_rules_section(existing, "rules content", "1.9.1")
        assert result.startswith("# My Project\n")
        assert "Custom instructions here." in result
        assert "FLASH:START" in result
        assert "rules content" in result

    def test_replaces_existing_flash_section(self):
        existing = (
            "# My Project\n"
            "<!-- FLASH:START - Auto-generated by runpod-flash 1.8.0. Do not edit. -->\n"
            "old rules\n"
            "<!-- FLASH:END -->\n"
        )
        result = inject_rules_section(existing, "new rules", "1.9.1")
        assert "old rules" not in result
        assert "new rules" in result
        assert result.count("FLASH:START") == 1

    def test_preserves_user_content_outside_markers(self):
        existing = (
            "# My Notes\nImportant stuff.\n\n"
            "<!-- FLASH:START - Auto-generated by runpod-flash 1.8.0. Do not edit. -->\n"
            "old rules\n"
            "<!-- FLASH:END -->\n"
            "\n# More notes\n"
        )
        result = inject_rules_section(existing, "new rules", "1.9.1")
        assert "# My Notes\nImportant stuff." in result
        assert "# More notes" in result

    def test_disabled_file_returns_none(self):
        existing = "# My Project\n<!-- FLASH:DISABLE -->\n"
        result = inject_rules_section(existing, "rules", "1.9.1")
        assert result is None

    def test_start_without_end_replaces_to_eof(self):
        existing = (
            "# My Project\n"
            "<!-- FLASH:START - Auto-generated by runpod-flash 1.8.0. Do not edit. -->\n"
            "orphan content with no end marker\n"
        )
        result = inject_rules_section(existing, "new rules", "1.9.1")
        assert "orphan content" not in result
        assert "new rules" in result
        assert "FLASH:END" in result

    def test_multiple_marker_pairs_uses_first(self):
        existing = (
            "<!-- FLASH:START - Auto-generated by runpod-flash 1.8.0. Do not edit. -->\n"
            "first section\n"
            "<!-- FLASH:END -->\n"
            "middle content\n"
            "<!-- FLASH:START - Auto-generated by runpod-flash 1.8.0. Do not edit. -->\n"
            "second section\n"
            "<!-- FLASH:END -->\n"
        )
        result = inject_rules_section(existing, "new rules", "1.9.1")
        assert "first section" not in result
        assert "new rules" in result
        assert "second section" in result

    def test_orphan_end_marker_appends_new_section(self):
        existing = "# My Project\n<!-- FLASH:END -->\nsome content\n"
        result = inject_rules_section(existing, "new rules", "1.9.1")
        assert "FLASH:START" in result
        assert "new rules" in result


class TestGenerateAgentFiles:
    def test_creates_all_agent_files_in_new_project(self, tmp_path: Path):
        generate_agent_files(tmp_path, "1.9.1")
        for target in AGENT_FILE_TARGETS:
            filepath = tmp_path / target
            assert filepath.exists(), f"Missing: {target}"
            content = filepath.read_text()
            assert "FLASH:START" in content
            assert "@Endpoint" in content

    def test_preserves_existing_user_content(self, tmp_path: Path):
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text("# My Custom Rules\nDo not delete me.\n")
        generate_agent_files(tmp_path, "1.9.1")
        content = claude_md.read_text()
        assert "# My Custom Rules" in content
        assert "Do not delete me." in content
        assert "FLASH:START" in content

    def test_skips_disabled_files(self, tmp_path: Path):
        claude_md = tmp_path / "CLAUDE.md"
        claude_md.write_text("<!-- FLASH:DISABLE -->\nMy content.\n")
        generate_agent_files(tmp_path, "1.9.1")
        content = claude_md.read_text()
        assert "FLASH:START" not in content
        assert "My content." in content

    def test_creates_github_directory_for_copilot(self, tmp_path: Path):
        generate_agent_files(tmp_path, "1.9.1")
        copilot_file = tmp_path / ".github" / "copilot-instructions.md"
        assert copilot_file.exists()

    def test_generates_placeholder_context_file(self, tmp_path: Path):
        generate_agent_files(tmp_path, "1.9.1")
        context_file = tmp_path / ".flash" / "context.md"
        assert context_file.exists()
        content = context_file.read_text()
        assert "flash run" in content or "flash build" in content


class TestUpdateDynamicContext:
    def test_writes_context_file_from_manifest(self, tmp_path: Path):
        manifest_data = {
            "version": "1.0",
            "resources": {
                "worker": {
                    "resource_type": "LiveServerless",
                    "file_path": "worker.py",
                    "functions": [
                        {
                            "name": "run",
                            "module": "worker",
                            "is_async": True,
                            "is_class": False,
                        }
                    ],
                    "is_load_balanced": False,
                    "makes_remote_calls": False,
                }
            },
            "function_registry": {"run": "worker"},
        }
        # Test root-level manifest location
        manifest_path = tmp_path / "flash_manifest.json"
        manifest_path.write_text(json.dumps(manifest_data))

        update_dynamic_context(tmp_path)

        context_file = tmp_path / ".flash" / "context.md"
        assert context_file.exists()
        content = context_file.read_text()
        assert "worker" in content
        assert "Auto-generated" in content

    def test_finds_manifest_in_dot_flash(self, tmp_path: Path):
        manifest_data = {
            "version": "1.0",
            "resources": {
                "gpu": {
                    "resource_type": "LiveServerless",
                    "file_path": "gpu.py",
                    "functions": [],
                    "is_load_balanced": False,
                    "makes_remote_calls": False,
                }
            },
            "function_registry": {},
        }
        manifest_path = tmp_path / ".flash" / "flash_manifest.json"
        manifest_path.parent.mkdir(parents=True, exist_ok=True)
        manifest_path.write_text(json.dumps(manifest_data))

        update_dynamic_context(tmp_path)

        context_file = tmp_path / ".flash" / "context.md"
        assert context_file.exists()
        assert "gpu" in context_file.read_text()

    def test_no_manifest_writes_placeholder(self, tmp_path: Path):
        update_dynamic_context(tmp_path)

        context_file = tmp_path / ".flash" / "context.md"
        assert context_file.exists()
        content = context_file.read_text()
        assert "flash run" in content or "flash build" in content
