"""Dynamic context rendering from Flash manifest data."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

MAX_DETAILED_ENDPOINTS = 20


def render_dynamic_context(manifest: dict[str, Any]) -> str:
    """Render .flash/context.md from manifest data."""
    resources = manifest.get("resources", {})
    timestamp = datetime.now(timezone.utc).isoformat()

    lines = [
        f"<!-- Auto-generated by flash at {timestamp} -->",
        "<!-- Do not edit. Regenerated on every flash command. -->",
        "",
    ]

    if not resources:
        lines.append(
            "No endpoints discovered. Add `@Endpoint` decorated functions to your project."
        )
        return "\n".join(lines) + "\n"

    # Endpoints table
    lines.append("## Endpoints")
    lines.append("")
    lines.append("| Name | Type | Resource | Workers | File |")
    lines.append("|------|------|----------|---------|------|")

    for name, res in resources.items():
        ep_type = "LB" if res.get("is_load_balanced") else "QB"
        res_type = res.get("resource_type", "unknown")
        gpu = res.get("gpuIds", "")
        workers_min = res.get("workersMin", "?")
        workers_max = res.get("workersMax", "?")
        workers = f"{workers_min}-{workers_max}" if workers_min != "?" else "?"
        file_path = res.get("file_path", "?")
        lines.append(
            f"| {name} | {ep_type} | {res_type} ({gpu}) | {workers} | {file_path} |"
        )

    lines.append("")

    # Dependency graph
    callers = {
        name: res for name, res in resources.items() if res.get("makes_remote_calls")
    }
    if callers:
        lines.append("## Dependency Graph")
        lines.append("")
        for name in callers:
            lines.append(f"- {name} (LB) makes remote calls to other endpoints")
        lines.append("")

    # Per-endpoint details (capped for token budget)
    lines.append("## Per-Endpoint Details")
    lines.append("")

    for idx, (name, res) in enumerate(resources.items()):
        if idx >= MAX_DETAILED_ENDPOINTS:
            remaining = len(resources) - MAX_DETAILED_ENDPOINTS
            lines.append(
                f"*...and {remaining} more endpoints (see flash_manifest.json for details)*"
            )
            break

        lines.append(f"### {name}")
        lines.append(f"- Type: {res.get('resource_type', 'unknown')}")
        if res.get("gpuIds"):
            lines.append(f"- GPU: {res['gpuIds']}")
        workers_min = res.get("workersMin")
        workers_max = res.get("workersMax")
        if workers_min is not None:
            lines.append(f"- Workers: {workers_min}-{workers_max}")
        lines.append(f"- Makes remote calls: {res.get('makes_remote_calls', False)}")

        funcs = res.get("functions", [])
        if funcs:
            func_names = [f["name"] for f in funcs]
            lines.append(f"- Functions: {', '.join(func_names)}")

        lines.append("")

    return "\n".join(lines) + "\n"
