"""Rules engine for generating AI agent context files."""

from __future__ import annotations

import logging
import re
from importlib import resources
from pathlib import Path

logger = logging.getLogger(__name__)

FLASH_START_MARKER = (
    "<!-- FLASH:START - Auto-generated by runpod-flash {version}. Do not edit. -->"
)
FLASH_END_MARKER = "<!-- FLASH:END -->"
FLASH_DISABLE_MARKER = "<!-- FLASH:DISABLE -->"
FLASH_REGENERATE_HINT = "<!-- Regenerate with: flash rules -->"

AGENT_FILE_TARGETS = [
    "CLAUDE.md",
    ".cursorrules",
    "AGENTS.md",
    ".github/copilot-instructions.md",
]

CONTEXT_PLACEHOLDER = (
    "<!-- Auto-generated by runpod-flash. -->\n"
    "<!-- Run `flash run` or `flash build` to populate project context. -->\n\n"
    "No project context available yet. Run a flash command to generate.\n"
)


def read_static_rules() -> str:
    """Read the bundled static rules content."""
    rules_file = resources.files("runpod_flash.rules") / "flash-rules.md"
    return rules_file.read_text(encoding="utf-8")


def inject_rules_section(
    existing_content: str,
    rules_content: str,
    version: str,
) -> str | None:
    """Inject or replace the Flash rules section in a file.

    Returns updated content, or None if file has FLASH:DISABLE.
    """
    if FLASH_DISABLE_MARKER in existing_content:
        return None

    start_marker = FLASH_START_MARKER.format(version=version)
    section = (
        f"{start_marker}\n"
        f"{FLASH_REGENERATE_HINT}\n\n"
        f"{rules_content}\n\n"
        f"## Current Project State\n\n"
        f"See `.flash/context.md` for live project context "
        f"(regenerated on each flash command).\n\n"
        f"{FLASH_END_MARKER}\n"
    )

    start_pattern = re.compile(
        r"^<!-- FLASH:START - Auto-generated by runpod-flash .+\. Do not edit\. -->",
        re.MULTILINE,
    )
    start_match = start_pattern.search(existing_content)

    if start_match:
        before = existing_content[: start_match.start()]
        after_start = existing_content[start_match.end() :]
        end_idx = after_start.find(FLASH_END_MARKER)
        if end_idx != -1:
            after = after_start[end_idx + len(FLASH_END_MARKER) :]
            if after.startswith("\n"):
                after = after[1:]
            return before + section + after
        else:
            return before + section
    else:
        if not existing_content or existing_content.isspace():
            return section
        separator = "" if existing_content.endswith("\n\n") else "\n"
        return existing_content.rstrip("\n") + "\n\n" + separator + section


def generate_agent_files(project_dir: Path, version: str) -> list[str]:
    """Generate platform-specific agent files with Flash rules."""
    rules_content = read_static_rules()
    written: list[str] = []

    for target in AGENT_FILE_TARGETS:
        filepath = project_dir / target
        filepath.parent.mkdir(parents=True, exist_ok=True)

        existing = ""
        if filepath.exists():
            existing = filepath.read_text(encoding="utf-8")

        result = inject_rules_section(existing, rules_content, version)
        if result is None:
            logger.info("Skipping %s (FLASH:DISABLE found)", target)
            continue

        filepath.write_text(result, encoding="utf-8")
        written.append(target)

    # Generate placeholder .flash/context.md
    context_dir = project_dir / ".flash"
    context_dir.mkdir(parents=True, exist_ok=True)
    context_file = context_dir / "context.md"
    if not context_file.exists():
        context_file.write_text(CONTEXT_PLACEHOLDER, encoding="utf-8")
        written.append(".flash/context.md")

    return written
